### ISSUE TITLE
support Mermaid

### ISSUE THREAD

**Issue by heycalmdown** [heycalmdown/miniseminar#15]
https://knsv.github.io/mermaid/

https://github.com/hakimel/reveal.js/issues/1082

Use the ability to pass customizable Markdown renderer from Reveal.js@3.4.0

**Comment by Scooletz** [comment]
I tried this approach with the setup included below. Unfortunately this works nicely only for the speaker notes view. The original slide is rendered badly. Does it require some additional styling?

<details>

    function markedLoaded(){
        var r = new marked.Renderer();
                        
        // mermaid
        r.code = function (code, language) {
            if(code.match(/^\nsequenceDiagram/)||code.match(/^\ngraph/)){
                return '<div class="mermaid">'+code+'</div>';
            }
            else{
                return '<pre><code>'+code+'</code></pre>';
            }
        };

        marked.setOptions({
            renderer: r});
    }

	Reveal.initialize({
        dependencies: [
            // Cross-browser shim that fully implements classList - https://github.com/eligrey/classList.js/
            { src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },

            // Interpret Markdown in <section> elements
            { src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); }, callback: markedLoaded },
            { src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },

            // Syntax highlight for <code> elements
            { src: 'plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },

            // Zoom in and out with Alt+click
            { src: 'plugin/zoom-js/zoom.js', async: true },

            // Speaker notes
            { src: 'plugin/notes/notes.js', async: true },

            // MathJax
            { src: 'plugin/math/math.js', async: true }
        ]
    });

    mermaid.initialize({startOnLoad:true});

</details>

**Comment by heycalmdown** [comment]
@Scooletz Despite what I've mentioned about `customizable Markdown renderer` before, I made it render out of Markdown support. Check what the last PR.
